import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import ToastContainer from "@/components/AlertMessages/Toast";
import ReactQueryProvider from "@/components/react-query-provider";
import { AuthCheck } from "@/components/authprovider";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // Specify weights you need
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "K7 Knowledge Organizer",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}
      >
        <NextIntlClientProvider messages={messages}>
          <ToastContainer />
          <ReactQueryProvider>
            <AuthCheck>{children}</AuthCheck>
          </ReactQueryProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
