# Use an official Python base image
FROM python:3.10.7

# Set environment variables to avoid interactive prompts
ENV DEBIAN_FRONTEND=noninteractive

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libgl1-mesa-glx \
    tesseract-ocr \
    libtesseract-dev \
    poppler-utils \
    && rm -rf /var/lib/apt/lists/*

# Copy the requirements.txt file into the container
COPY requirements.txt .


# Install Python dependencies
RUN pip install -r requirements.txt

# Set the working directory
WORKDIR /app


# Copy local files into the container
COPY . .

# Expose port 8000 for FastAPI
EXPOSE 8000

# Run Uvicorn server when the container starts
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
